# Generated by Django 4.2.16 on 2024-10-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_bookinstance_borrower"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="author_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
